# Generated by Django 2.1.7 on 2019-03-27 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='c_Setting',
        ),
    ]
