# Generated by Django 2.1.7 on 2019-04-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190327_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_setting',
            name='sett_backup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='c_setting',
            name='sett_restore',
            field=models.TextField(blank=True, null=True),
        ),
    ]
