# Generated by Django 2.1.7 on 2019-05-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190413_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_setting',
            name='sett_vlan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
